services:
  db:
    image: postgres:15-alpine

    restart: unless-stopped

    environment:
      - POSTGRES_USER=uptime
      - POSTGRES_PASSWORD=Onepiece1099
      - POSTGRES_DB=uptime_db
    
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data:
